### ISSUE TITLE
Version 8.1.0 sends no label to loki

### ISSUE THREAD

**Issue by CrosRoad95** [serilog-contrib/serilog-sinks-grafana-loki#204]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v8.1.0

### Which version of .NET are you using?

net8.0

### Describe the bug

Created most basic serilog logger with this exported and i noticed no logs being send to the loki. When i downgraded to 7.1.1 it worked.
But if i had letf version 8.1.0 it partially worked when i provide labels in "GrafanaLoki" method example "level" value for "propertiesAsLabel" manually, but then logs doesn't format properly in loki, i see template instead of rendered message.

Looked even into code to find maybe some flag like "treat all properties as labels"

### To Reproduce

just use newest version 8.1.0, it won't work as expected. If you use custom http client you will see "400" bad request

### Expected behavior

Version 8.1.0 should by default export all labels

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
Hi @CrosRoad95!

Could you please confirm that you have read [v8 breaking changes](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Breaking-changes#v8) and [explanation behind them](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/discussions/99)?

If yes, please, provide the configuration part for your logger. 

Thanks!

**Comment by mishamyte** [comment]
> Looked even into code to find maybe some flag like "treat all properties as labels"

That flag will not exist, because it's the wrong way of using Loki (check pls [best practices](https://grafana.com/blog/2020/04/21/how-labels-in-loki-can-make-log-queries-faster-and-easier/#best-practices)) and will lead to the high cardinality problem.

I would suggest check the [Using LokiJsonTextFormatter and Grafana Loki json parser
](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Using-LokiJsonTextFormatter-and-Grafana-Loki-json-parser) article
