### ISSUE TITLE
Question about resiliency/ failsafe

### ISSUE THREAD

**Issue by luizfbicalho** [serilog-contrib/serilog-sinks-grafana-loki#92]
I read in many places that we should save all the logs to files and then after export them do grafana, this way we would have the safest way to log everything.

Is there a failsafe strategy that I can use with this sink? or there is something implemented inside it?

**Comment by mishamyte** [comment]
Hi @luizfbicalho,

The functionality, which used intermediate file to store the logs was in the previous versions of this sink and was deleted due to unavailability to process _data as a log stream (with labels)_ for Loki correctly.

Now sinks handles situations of network issues/Loki temporary unavailability/etc, providing in memory buffer for log stream, which implements retry strategies to prevent data loss, related to Loki unavailability. So this would help in cases of low-middle downtime of Loki. It does not save you from data loss in case of Loki unavailability + shutdown of log producer process (your service). 

The main idea is to do a periodic batching frequently. By default this sink batches up to 1000 log events every 1s, but this values could be adjusted, according to your system requirements and needs.

Also you could give a look to a [Promtail](https://grafana.com/docs/loki/latest/clients/promtail/), as a client, developed by Grafana labs

**Comment by luizfbicalho** [comment]
Thanks,

The promtail work with this sink or it's another one?

If I use Polly [https://github.com/App-vNext/Polly](https://github.com/App-vNext/Polly) im my project this sink will use it too?

**Comment by mishamyte** [comment]
@luizfbicalho I think it would be useful to read how Promtail works and what is required.

In short, it parsed log files, so u could use any sink, which could write into the files.

Also I strongly recommend to read about structured logging and decide would it be useful for your business needs.

> If I use Polly https://github.com/App-vNext/Polly im my project this sink will use it too?

You could fully control creating and customizing of HttpClient. It you need more customization, `ILokiHttpClient ` could be implemented and passed to the sink

**Comment by luizfbicalho** [comment]
Thanks for all the answers, I believe for now I'll use the default sink and see how it works
